### ISSUE TITLE
Installing requirements fails at installation of MarkupSafe 1.0

### ISSUE THREAD

**Issue by PeteGierth** [amm042/qsched#21]
System info: Ubuntu 22.04.3, python 3.10.9

Steps to reproduce:
Download code as zipfile and extract
In bash shell, enter qsched-master folder
Setup venv with _python3 -m venv new_venv_
Activate with _source new_venv/bin/activate_
Install required python components with _pip install -r requirements.txt_

Expected result:
Python components installed correctly

Actual result:
Installation of python components stops at MarkupSafe, with error:

Collecting MarkupSafe==1.0
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dkdi2xpk/markupsafe_0322937cd8c64c2cb6145e38ee1c7fc2/setup.py", line 6, in <module>
          from setuptools import setup, Extension, Feature
      ImportError: cannot import name 'Feature' from 'setuptools' (/home/nmr/qsched-master/new_venv/lib/python3.10/site-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Attempts to resolve:
Specifying MarkupSafe 1.1.1 in requirements.txt gets past this problem, but then pkg-resources==0.0.0 causes failure; removing that leads to troposphere failing with

 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in troposphere setup command: use_2to3 is invalid.
      [end of output]

and in the end it seems impossible to get to a working collection of packages.

Possibly installing an older python version would solve the problem, but that's not trivial.

NB the reason I'm trying to install this locally, is because the web version seems not to be working.

**Comment by amm042** [comment]
I'm not entirely sure about the python error, but the web version is working from me at this url: http://qsched.bison.link/

What happens when you try the web version?

**Comment by amm042** [comment]
Ok it is not running off another link I found, interesting.

Use the short link above and/or run the file qsched_098.py locally [after installing the needed dependencies]. That is the scheduling algorithm. You don't need the whole web interface to run it locally, and the web part is more difficult to setup.

let met know if you have any more problems.
